apiVersion: v1
kind: ConfigMap
metadata:
  name: jobset-controller-config
  namespace: jobset-system
  labels:
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/version: "0.7.3"
    app.kubernetes.io/name: jobset
    app.kubernetes.io/instance: jobset
    app.kubernetes.io/component: controller
data:
  controller_manager_config.yaml: |2
    apiVersion: config.jobset.x-k8s.io/v1alpha1
    kind: Configuration
    leaderElection:
      leaderElect: true
    clientConnection:
      qps: 500
      burst: 500
    internalCertManagement:
      enable: false
      webhookServiceName: jobset-webhook-service
      webhookSecretName: jobset-webhook-server-cert
