apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jobset-cert
  namespace: jobset-system
  labels:
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/version: "0.7.3"
    app.kubernetes.io/name: jobset
    app.kubernetes.io/instance: jobset
spec:
  secretName: jobset-webhook-server-cert
  issuerRef:
    group: cert-manager.io/v1
    kind: Issuer
    name: jobset-self-signed-issuer
  commonName: jobset-webhook-service.jobset-system.svc
  dnsNames:
    - jobset-webhook-service.jobset-system.svc
    - jobset-webhook-service.jobset-system.svc.cluster.local
  duration: 8760h
  renewBefore: 720h
  usages:
    - server auth
    - client auth
