# more details can be found  https://github.com/kubernetes-sigs/reference-docs/tree/master/genref
hiddenMemberFields:
  - "TypeMeta"
  - "ObjectMeta"

apis:
  - name: jobset
    title: JobSet API
    package: sigs.k8s.io/jobset
    path: api/jobset/v1alpha2

externalPackages:
  - match: ^k8s\.io/(api|apimachinery/pkg/apis)/
    target: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#{{- lower .TypeIdentifier -}}-{{- arrIndex .PackageSegments -1 -}}-{{- arrIndex .PackageSegments -2 -}}
  - match: ^k8s\.io/apimachinery/pkg/api/resource\.Quantity$
    target: https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#Quantity
  - match: ^k8s.io/component-base/config/v1alpha1.
    target: https://pkg.go.dev/k8s.io/component-base/config/v1alpha1#{{- .TypeIdentifier -}}
  - match: ^time\.Duration$
    target: https://pkg.go.dev/time#Duration
