apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  labels:
    app.kubernetes.io/name: jobset
    app.kubernetes.io/instance: jobset-sample
    app.kubernetes.io/part-of: jobset
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: jobset
  name: jobset-sample
spec:
  # TODO(user): Add fields here