# permissions for end users to view jobsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jobset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/part-of: jobset
  name: jobset-viewer-role
rules:
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets/status
  verbs:
  - get
