# permissions for end users to edit jobsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jobset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/part-of: jobset
  name: jobset-editor-role
rules:
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets/status
  verbs:
  - get
